[scripts]
# Gets the ID of a running Docker container by its name (utility script)
getcontainerid.cmd = "docker ps | awk -v containername=\"%containername\" '$0 ~ containername{print $1}'"
getcontainerid.args = [
    "containername"
]
# Use this script to run any `docker-compose` commands, it automatically interpolates environment variables
dc = "docker-compose --env-file .ports.env %%"
# Rebuilds all containers, use this when you change any Docker configurations or update Rust dependencies
rebuild = "bonnie dc up --build -d"
# Starts all containers without creating a shell
up = "bonnie dc up -d"
# Opens a shell into the Docker container (doesn't build, so should be super-fast)
sh = "bonnie up && docker attach $(bonnie getcontainerid diana.playground)"
# Brings down all Docker containers
end = "bonnie dc down"

# Scripts for individual containers
start-server = "bonnie dc up -d server"
stop-server = "bonnie dc stop server"
attach-server = "bonnie up-server && docker attach $(bonnie getcontainerid diana.server)"
sh-server = "bonnie dc run --entrypoint \"/bin/zsh\" -p 9001:7000 --use-aliases --rm server"
start-subscriptions-server = "bonnie dc up -d subscriptions-server"
stop-subscriptions-server = "bonnie dc stop subscriptions-server"
attach-subscriptions-server = "bonnie up-subscriptions-server && docker attach $(bonnie getcontainerid diana.subscriptions-server)"
sh-subscriptions-server = "bonnie dc run --entrypoint \"/bin/zsh\" -p 9002:6000 --use-aliases --rm subscriptions-server"

# Releases the project to GitHub
release = "standard-version && git push --follow-tags origin main"
