version = "0.2.0"

[scripts]
# Gets the ID of a running Docker container by its name (utility script)
getcontainerid.cmd = "docker ps | awk -v containername=\"%containername\" '$0 ~ containername{print $1}'"
getcontainerid.args = [
    "containername"
]

# Docker scripts
dc = "docker-compose %%"
rebuild = "bonnie dc up --build -d && bonnie dc down" # Use this when you change any Docker configurations or update Rust dependencies
up = "bonnie dc up -d"
end = "bonnie dc down"
sh = "bonnie dc run --entrypoint \"/bin/zsh\" --use-aliases --rm playground"

# General Rust scripts
doc = "cargo doc"
test = "cargo watch -x \"test\""
dev = "cargo watch -x \"check\""
check = "cargo check --all && cargo fmt --all -- --check && cargo clippy --all && cargo test --all" # This will be run on CI as well (ignoring expensive tests)
example = { cmd = "cargo watch -x \"run --example %example_name\"", args = ["example_name"] }
serverless-compile = "cd examples/netlify && sh build.sh"
serverless-deploy = "bonnie serverless compile && netlify deploy --prod"

# Releases the project to GitHub (doesn't publish the crates)
release = "standard-version --sign --commit-all && git push --follow-tags origin main"
publish-core = "cargo publish"
publish-integrations = "cd integrations/serverful/actix-web && cargo publish && cd ../../serverless/aws-lambda && cargo publish"
