# Managing the API with workspaces allows us to run multiple systems in parallel
[workspace]
members = [
    "lib",
    "graphql_server",
    "subscriptions_server",
    "dev_utils" # The DB logic etc. for testing in a realistic way
]
