version: "3.7"
services:
    playground:
        image: diana.playground
        container_name: diana.playground
        build:
            context: ./
            target: playground # We use the playground stage of the Dockerfile so we get a terminal prompt
        volumes:
            # Binds your app code into the container so changes you make are reflected instantly
            - type: bind
              source: ./
              target: /app
        # Allows this container to be accessed with a terminal for debugging
        stdin_open: true
        tty: true
    server:
        image: diana.server
        container_name: diana.server
        build:
            context: ./
            target: server # We use the server stage of the Dockerfile so we get a terminal prompt
        ports:
            - "127.0.0.1:${SERVER_PORT}:7000"
        volumes:
            # Binds your app code into the container so changes you make are reflected instantly
            - type: bind
              source: ./
              target: /app
        depends_on:
            - db # The DB must be started before this container can come up
            # - subscriptions-server # If you're not using subscriptions, remove this line
        # Allows this container to be accessed with a terminal for debugging
        stdin_open: true
        tty: true
    serverless:
        image: diana.serverless
        container_name: diana.serverless
        build:
            context: ./
            target: serverless # We use the serverless stage of the Dockerfile so we get a terminal prompt
        ports:
            - "127.0.0.1:${SERVERLESS_PORT}:5000"
        volumes:
            # Binds your app code into the container so changes you make are reflected instantly
            - type: bind
              source: ./
              target: /app
        depends_on:
            - db # The DB must be started before this container can come up
            # - subscriptions-server # If you're not using subscriptions, remove this line
        # Allows this container to be accessed with a terminal for debugging
        stdin_open: true
        tty: true
    subscriptions-server:
        image: diana.subscriptions-server
        container_name: diana.subscriptions-server
        build:
            context: ./
            target: subscriptions_server # We use the subscriptions-server stage of the Dockerfile so we get a terminal prompt
        ports:
            - "127.0.0.1:${SUBSCRIPTIONS_SERVER_PORT}:6000"
        volumes:
            # Binds your app code into the container so changes you make are reflected instantly
            - type: bind
              source: ./
              target: /app
        depends_on:
            - db # The DB must be started before this container can come up
        # Allows this container to be accessed with a terminal for debugging
        stdin_open: true
        tty: true
    # Creates a DB for development, which will run entirely isolated in Docker
    # When you switch to a production DB, this is redundant, it's only useful for development
    # This is started by Bonnie automatically
    db:
        image: mongo:latest
        container_name: diana.db
        ports:
            - "127.0.0.1:${DB_PORT}:27017" # Anything running on 0.0.0.0:27017 in the container gets forwarded to localhost:${APP_PORT} on the host
        env_file: examples/.env.local # DB credentials stored in the API secrets file are used to initialise the DB with a username and password
        # Set up an internal Docker volume for the MongoDB data so that it persists across container restarts (stored internally by Docker)
        volumes:
            - "db-data:/data/db"

volumes:
    db-data:
        name: diana-db
