version: "3.7"
services:
    playground:
        image: diana.playground
        container_name: diana.playground
        build:
            context: ./
            target: playground
        network_mode: host # So we don't have to deal with port management
        volumes:
            - type: bind
              source: ./
              target: /app
        stdin_open: true
        tty: true
