version: "3.7"
services:
    playground:
        image: diana.playground
        container_name: diana.playground
        build:
            context: ./
            target: playground
        ports:
            - "127.0.0.1:${SERVER_PORT}:7000"
            - "127.0.0.1:${SUBSCRIPTIONS_SERVER_PORT}:6000"
            # Serverless is tested by deployment only at the moment because `netlify dev` doesn't support Rust functions
        volumes:
            - type: bind
              source: ./
              target: /app
        stdin_open: true
        tty: true
