name: Test

on: [push, pull_request]

jobs:
    lib:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test Library
              run: cargo check && cargo fmt -- --check && cargo clippy && cargo test
    examples:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test Examples
              run: cargo check && cargo fmt -- --check && cargo clippy && cargo test
              working-directory: examples/
