name: Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test Library
              run: cargo check --all && cargo fmt --all -- --check && cargo clippy --all && cargo test --all
